# === 基本設置 ===
# 網站名稱，會顯示在瀏覽器標籤和導航列
site_name: 一個導航站
# 網站 URL，通常是 GitHub Pages 的位址
site_url: https://nav-site.windwater.info 
# 作者資訊
#site_author: 
# 網站描述，用於 SEO
site_description: 一個書籤收集導航站

# === 主題設置 ===
theme:
  # 使用 Material 主題
  name: material
  # 設定語言為繁體中文
  language: zh-Hant
  # 設定網站 logo（路徑相對於 docs 目錄）
  #logo: assets/logo.png
  # 設定網站圖示
  #favicon: assets/square-code.png

  # ----- 功能設定 -----
  features:
    # === 導航功能 ===
    - navigation.tabs      # 頂部顯示主要分類標籤
    - navigation.sections  # 側邊欄分區顯示
    - navigation.expand    # 自動展開導航項
    - navigation.top       # 顯示返回頂部按鈕
#    - navigation.footer    # 顯示頁腳導航
    - toc.follow           # 目錄跟隨滾動
    
    # === 搜尋功能 ===
    - search.highlight     # 搜尋結果高亮顯示
    - search.share         # 可分享搜尋結果
    - search.suggest       # 搜尋建議
    
    # === 內容功能 ===
    - content.code.copy    # 程式碼區塊可複製
    - content.tabs.link    # 分頁內容可連結
    
    # === 進階功能 ===
    - navigation.tracking  # 跟蹤導航位置
    - navigation.instant   # 即時頁面切換
    - header.autohide      # 滾動時自動隱藏頁首
    - announce.dismiss     # 可關閉公告

  # ----- 配色方案 -----
  palette:
    # === 亮色主題 ===
    - media: "(prefers-color-scheme: light)"  # 系統使用亮色模式時
      scheme: default                         # 使用默認配色
      primary: blue                           # 主要顏色
      accent: deep orange                     # 強調顏色
      toggle:
        icon: material/weather-sunny          # 切換按鈕圖示
        name: 切換至深色模式                  # 切換按鈕提示文字
    
    # === 暗色主題 ===
    - media: "(prefers-color-scheme: dark)"   # 系統使用暗色模式時
      scheme: slate                           # 使用石板配色
      primary: indigo                         # 主要顏色
      accent: deep orange                     # 強調顏色
      toggle:
        icon: material/weather-night          # 切換按鈕圖示
        name: 切換至淺色模式                  # 切換按鈕提示文字

# === 定義網站的導航結構 ===
nav:
  - '首頁': 'index.md'
  - 'Windows 常用軟體':
    - '2-1.安裝包管理器': 'windows_software/2-1_package_manager/package_manager.md'
    - '2-2.執行環境': 'windows_software/2-2_runtime_Environments/runtime_Environments.md'
    - '2-3.系統類':
        - '2-3-1.系統資訊查詢': 'windows_software/2-3_system/2-3-1_system_info/system_info.md'
  - '字型專案': 'fonts.md'
  - '測試頁': 
    - 'folder/page02.md'
    - 'folder/page03.md'
